#!/bin/bash -f

run=(try)

output_columns="thread thread_start_time_sec thread_start_time_nsec thread_stop_time_sec thread_stop_time_nsec global_start_time_sec global_start_time_nsec global_stop_time_sec global_stop_time_nsec"

try=`seq 1 10`				# Number of different run per setting

compile=(maxiter width height lower_r upper_r lower_i upper_i nb_thread loadbalance)

maxiter=256 				# int max: 2147483647
width=500
height=375
lower_r=-2
upper_r=0.6
lower_i=-1
upper_i=1
nb_thread=`seq 0 6`			# From 0 (sequential) to 6 threads
loadbalance="0 1"

## Do not run sequential version with load-balancing strategies
restrict="! ( match(nb_thread, \"^0\$\") && ! match(loadbalance, \"^0\$\") )"

## Give labels to each parameter value
labels_nb_thread="0: Seq.; 1: Over."
labels_thread="0: Thread 1 (seq.); 1: Thread 1; 2: Thread 2; 3: Thread 3; 4: Thread 4; 5: Thread 5; 6: Thread 6; 7: Thread 7; 8: Thread 8"
labels_loadbalance="0: Naive; 1: Load-balanced (mandatory); 2: Load-balanced (optional)"
labels_columns="nb_thread: Number of threads"

